// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/superproj/zero/internal/usercenter/biz (interfaces: BizFactory)

// Package biz is a generated GoMock package.
package biz

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	auth "github.com/superproj/zero/internal/usercenter/biz/auth"
	secret "github.com/superproj/zero/internal/usercenter/biz/secret"
	user "github.com/superproj/zero/internal/usercenter/biz/user"
)

// MockBizFactory is a mock of BizFactory interface.
type MockBizFactory struct {
	ctrl     *gomock.Controller
	recorder *MockBizFactoryMockRecorder
}

// MockBizFactoryMockRecorder is the mock recorder for MockBizFactory.
type MockBizFactoryMockRecorder struct {
	mock *MockBizFactory
}

// NewMockBizFactory creates a new mock instance.
func NewMockBizFactory(ctrl *gomock.Controller) *MockBizFactory {
	mock := &MockBizFactory{ctrl: ctrl}
	mock.recorder = &MockBizFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBizFactory) EXPECT() *MockBizFactoryMockRecorder {
	return m.recorder
}

// Auths mocks base method.
func (m *MockBizFactory) Auths() auth.AuthBiz {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Auths")
	ret0, _ := ret[0].(auth.AuthBiz)
	return ret0
}

// Auths indicates an expected call of Auths.
func (mr *MockBizFactoryMockRecorder) Auths() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Auths", reflect.TypeOf((*MockBizFactory)(nil).Auths))
}

// Secrets mocks base method.
func (m *MockBizFactory) Secrets() secret.SecretBiz {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Secrets")
	ret0, _ := ret[0].(secret.SecretBiz)
	return ret0
}

// Secrets indicates an expected call of Secrets.
func (mr *MockBizFactoryMockRecorder) Secrets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Secrets", reflect.TypeOf((*MockBizFactory)(nil).Secrets))
}

// Users mocks base method.
func (m *MockBizFactory) Users() user.UserBiz {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Users")
	ret0, _ := ret[0].(user.UserBiz)
	return ret0
}

// Users indicates an expected call of Users.
func (mr *MockBizFactoryMockRecorder) Users() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Users", reflect.TypeOf((*MockBizFactory)(nil).Users))
}
