// Copyright 2022 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/superproj/zero.
//

// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package nightwatch

import (
	store2 "github.com/superproj/zero/internal/gateway/store"
	"github.com/superproj/zero/internal/pkg/client/store"
	store3 "github.com/superproj/zero/internal/usercenter/store"
	"github.com/superproj/zero/pkg/db"

	_ "github.com/superproj/zero/internal/nightwatch/watcher/all"
)

// Injectors from wire.go:

func wireStoreClient(mySQLOptions *db.MySQLOptions) (store.Interface, error) {
	gormDB, err := db.NewMySQL(mySQLOptions)
	if err != nil {
		return nil, err
	}
	datastore := store2.NewStore(gormDB)
	storeDatastore := store3.NewStore(gormDB)
	datastore2 := store.NewStore(datastore, storeDatastore)
	return datastore2, nil
}
