// Copyright 2022 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/superproj/zero.
//

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSecretM = "secret"

// SecretM mapped from table <secret>
type SecretM struct {
	ID          int64     `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id"`
	UserID      string    `gorm:"column:userID;type:varchar(253);not null;index:idx_userID,priority:1" json:"userID"`
	Name        string    `gorm:"column:name;type:varchar(253);not null" json:"name"`
	SecretID    string    `gorm:"column:secretID;type:varchar(36);not null;uniqueIndex:uniq_secretID,priority:1" json:"secretID"`
	SecretKey   string    `gorm:"column:secretKey;type:varchar(36);not null" json:"secretKey"`
	Status      int32     `gorm:"column:status;type:int(2);default:1" json:"status"`
	Description string    `gorm:"column:description;type:varchar(255);not null" json:"description"`
	CreatedAt   time.Time `gorm:"column:createdAt;type:timestamp;not null;default:current_timestamp()" json:"createdAt"`
	UpdatedAt   time.Time `gorm:"column:updatedAt;type:timestamp;not null;default:current_timestamp()" json:"updatedAt"`
	Expires     int64     `gorm:"column:expires;type:bigint(64);not null" json:"expires"`
}

// TableName SecretM's table name
func (*SecretM) TableName() string {
	return TableNameSecretM
}
