// Copyright 2022 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/superproj/zero.
//

package app

import (
	utilruntime "k8s.io/apimachinery/pkg/util/runtime"
	genericapiserver "k8s.io/apiserver/pkg/server"
	logsapi "k8s.io/component-base/logs/api/v1"

	"github.com/superproj/zero/cmd/zero-pump/app/options"
	"github.com/superproj/zero/internal/pkg/feature"
	"github.com/superproj/zero/internal/pump"
	"github.com/superproj/zero/pkg/app"
)

func init() {
	utilruntime.Must(logsapi.AddFeatureGates(feature.DefaultMutableFeatureGate))
}

const commandDesc = `Pump is a pluggable analytics purger to move Analytics generated by your zero nodes to any back-end.

Find more zero-pump information at:
    https://github.com/superproj/zero/blob/master/docs/guide/en-US/cmd/zero-pump.md`

// NewApp creates an App object with default parameters.
func NewApp(name string) *app.App {
	opts := options.NewOptions()
	application := app.NewApp(name, "Launch a zero pump server",
		app.WithDescription(commandDesc),
		app.WithOptions(opts),
		app.WithDefaultValidArgs(),
		app.WithRunFunc(run(opts)),
	)

	return application
}

func run(opts *options.Options) app.RunFunc {
	return func() error {
		cfg, err := opts.Config()
		if err != nil {
			return err
		}

		return Run(cfg, genericapiserver.SetupSignalHandler())
	}
}

// Run runs the specified APIServer. This should never exit.
func Run(c *pump.Config, stopCh <-chan struct{}) error {
	server, err := c.Complete().New()
	if err != nil {
		return err
	}

	go c.HealthOptions.ServeHealthCheck()

	return server.PrepareRun().Run(stopCh)
}
