// Copyright 2022 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/superproj/zero.
//

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMinerSetM = "minerset"

// MinerSetM mapped from table <minerset>
type MinerSetM struct {
	ID                   int64     `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id"`
	Namespace            string    `gorm:"column:namespace;type:varchar(253);not null;uniqueIndex:uniq_namespace_name,priority:1" json:"namespace"`
	Name                 string    `gorm:"column:name;type:varchar(253);not null;uniqueIndex:uniq_namespace_name,priority:2" json:"name"`
	Replicas             int32     `gorm:"column:replicas;type:int(8);not null" json:"replicas"`
	DisplayName          string    `gorm:"column:displayName;type:varchar(253);not null" json:"displayName"`
	DeletePolicy         string    `gorm:"column:deletePolicy;type:varchar(32);not null" json:"deletePolicy"`
	MinReadySeconds      int32     `gorm:"column:minReadySeconds;type:int(8);not null" json:"minReadySeconds"`
	FullyLabeledReplicas int32     `gorm:"column:fullyLabeledReplicas;type:int(8)" json:"fullyLabeledReplicas"`
	ReadyReplicas        int32     `gorm:"column:readyReplicas;type:int(8)" json:"readyReplicas"`
	AvailableReplicas    int32     `gorm:"column:availableReplicas;type:int(8)" json:"availableReplicas"`
	FailureReason        string    `gorm:"column:failureReason;type:longtext" json:"failureReason"`
	FailureMessage       string    `gorm:"column:failureMessage;type:longtext" json:"failureMessage"`
	Conditions           string    `gorm:"column:conditions;type:longtext" json:"conditions"`
	CreatedAt            time.Time `gorm:"column:createdAt;type:timestamp;not null;default:current_timestamp()" json:"createdAt"`
	UpdatedAt            time.Time `gorm:"column:updatedAt;type:timestamp;not null;default:current_timestamp()" json:"updatedAt"`
}

// TableName MinerSetM's table name
func (*MinerSetM) TableName() string {
	return TableNameMinerSetM
}
