// Copyright 2022 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/superproj/zero.
//

// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// user
func IsUserLoginFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserLoginFailed.String() && e.Code == 401
}

// user
func ErrorUserLoginFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_UserLoginFailed.String(), fmt.Sprintf(format, args...))
}

func IsUserAlreadyExists(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserAlreadyExists.String() && e.Code == 409
}

func ErrorUserAlreadyExists(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_UserAlreadyExists.String(), fmt.Sprintf(format, args...))
}

func IsUserNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserNotFound.String() && e.Code == 404
}

func ErrorUserNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_UserNotFound.String(), fmt.Sprintf(format, args...))
}

func IsUserCreateFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserCreateFailed.String() && e.Code == 541
}

func ErrorUserCreateFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(541, ErrorReason_UserCreateFailed.String(), fmt.Sprintf(format, args...))
}

func IsUserOperationForbidden(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserOperationForbidden.String() && e.Code == 403
}

func ErrorUserOperationForbidden(format string, args ...interface{}) *errors.Error {
	return errors.New(403, ErrorReason_UserOperationForbidden.String(), fmt.Sprintf(format, args...))
}

// secret
// Secret reach the max count
func IsSecretReachMaxCount(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_SecretReachMaxCount.String() && e.Code == 400
}

// secret
// Secret reach the max count
func ErrorSecretReachMaxCount(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_SecretReachMaxCount.String(), fmt.Sprintf(format, args...))
}

func IsSecretNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_SecretNotFound.String() && e.Code == 404
}

func ErrorSecretNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_SecretNotFound.String(), fmt.Sprintf(format, args...))
}

func IsSecretCreateFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_SecretCreateFailed.String() && e.Code == 541
}

func ErrorSecretCreateFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(541, ErrorReason_SecretCreateFailed.String(), fmt.Sprintf(format, args...))
}
