# Copyright 2022 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file. The original repo for
# this file is https://github.com/superproj/zero.
#


apiVersion: minercontroller.config.zero.io/v1beta1
kind: MinerControllerConfiguration
leaderElection:
  leaderElect: false
metricsBindAddress: 0.0.0.0:20349
healthzBindAddress: 0.0.0.0:20350
redis:
  addr: 127.0.0.1:6379
  database: 0
  password: zero(#)666
types:
  S1.SMALL1: 
    # CPU, in cores. (500m = .5 cores)
    cpu: 50m
    # Memory, in bytes. (500Gi = 500GiB = 500 * 1024 * 1024 * 1024)
    memory: 1024Mi
    miningDifficulty: 1
  S1.SMALL2: 
    cpu: 100m
    memory: 1024Mi
    miningDifficulty: 1
  M1.MEDIUM1: 
    cpu: 150m
    memory: 1024Mi
    miningDifficulty: 1
  M1.MEDIUM2: 
    cpu: 200m
    memory: 2048Mi
    miningDifficulty: 1
