# Copyright 2022 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file. The original repo for
# this file is https://github.com/superproj/zero.
#

# zero-nightwatch 服务配置文件

kubeconfig: /opt/zero/conf/config
db:
  host: 127.0.0.1 # 数据库主机地址
  username: zero # 数据库用户名
  password: zero(#)666 # 数据库密码
  database: zero # 数据库名称
  log-level: 4 # 数据库日志级别，1 为最低，4 为最高
health:
  enable-http-profiler: true
  check-path: /healthz
  check-address: 0.0.0.0:8080
redis:
  addr: 127.0.0.1:6379 # Redis 地址
  database: 0 # Redis 数据库索引
  password: zero(#)666 # Redis 密码
log:
    level: debug # 日志级别，优先级从低到高依次为：debug, info, warn, error, dpanic, panic, fatal。
    format: console # 支持的日志输出格式，目前支持 console 和 json 两种。console 其实就是 text 格式。
    enable-color: true # 是否开启颜色输出，true: 是，false: 否
    disable-caller: false # 是否开启 caller，如果开启会在日志中显示调用日志所在的文件、函数和行号
    disable-stacktrace: false # 是否再 panic 及以上级别禁止打印堆栈信息
    output-paths: [stdout] # 多个输出，逗号分开。stdout：标准输出，


